Monitoring 1
Otus-DevOps-2018-05/VladimirDe_microservices pull request #10
Opened 2018-11-02 09:17 UTC by VladimirDe

# Выполнено ДЗ №18

- [ ]   Основное ДЗ: запуск, конфигурация Prometheus; мониторинг состояния микросервисов; сбор метрик хоста с использованием экспортера
- [ ]   Задание со *: добавить в Prometheus мониторинг mongodb, зафиксировав версию образа экспортера на последнюю стабильную
- [ ]   Задание со *: добавить в Prometheus blackbox мониторинг сервисов comment, post, ui, зафиксировав версию образа экспортера на последнюю стабильную
- [ ]   Задание со *: добавить Makefile, которые умеет собирать и пушить образы docker контейнеров

## В процессе сделано:

- Изменена структура каталогов проекта, добавлены каталоги docker, monitoring
- В конфигурацию docker compose добавлен сервис prometheus
- В конфигурацию prometheus и docker compose добавлен node-exporter
- Добавлен Dockerfile для сборки mongodb prometheus exporter от percona (результирующий образ построен на scratch), добавлен мониторинг mongodb в prometheus и docker compose
- Добавлен Dockerfile для сборки blackbox exporter; добавлен мониторинг микросервисов ui (blackbox-http), post (blackbox-tcp), comment (blackbox-tcp)
- Добавлен Makefile для сборки образов docker контейнеров и их пуша в docker hub; добавлена возможность старта и удаления микросервисов через Makefile 
Ссылка на docker hub https://hub.docker.com/r/vladimirdenisov69

## Как запустить проект:

Описано в 18.2 Как запустить проект в README.md

## Как проверить работоспособность:

Описано в 18.3 Как проверить проект в README.md

## PR checklist

- [ ]   Выставил label с темой домашнего задания (Monitoring, monitoring-1)

2018-11-06 12:00 UTC, grim-yawn requested changes

2018-11-06 12:00 UTC, grim-yawn commented on docker/docker-compose-monitoring.yml
> +      - GMAIL_ACCOUNT=fisakov.root@gmail.com
Вот тут возможно стоит поправить адрес?
Возможно даже вынести его и токен в переменные окружения

2018-11-06 12:02 UTC, grim-yawn requested changes
Похоже сюда уполз код из monitoring-2

2018-11-07 11:00 UTC, VladimirDe commented
создам заново ветку monitoring-1 c ci-gitlab-2

2018-11-07 12:09 UTC, VladimirDe commented
Ещё один рывок, ещё одна попытка :)

2018-11-07 13:14 UTC, grim-yawn approved these changes
Теперь вроде ок 👍

2018-11-07 13:30 UTC, merged